apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventure-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: adventure

  template:
    metadata:
      labels:
        app: adventure

    spec:
      containers:
      - name: adventure

        image: saikiran2233/magicworld:latest

        env:
        - name: DB_HOST
          value: mysql

        ports:
        - containerPort: 3000
